//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainCenter.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Abonement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonement()
        {
            this.Visitings = new HashSet<Visiting>();
        }


        public int id { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> TrainigsNumber { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }

        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visiting> Visitings { get; set; }


        public Abonement(int personId, int trainingsNumber, DateTime endDate)
        {
            this.PersonId = personId;
            this.TrainigsNumber = trainingsNumber;
            this.EndDate = endDate;

        }
    }
}
