//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainCenter.Model
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media.TextFormatting;

    public partial class TrainProgram
    {
        public int id { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Text { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public string Title { get; set; }

        public virtual User User { get; set; }


        public TrainProgram()
        {

        }

        public TrainProgram(int personId, string title, string text, TimeSpan startTime, TimeSpan endTime, bool isDone)
        {
            this.PersonId = personId;
            this.Text = text;
            this.StartTime = startTime;
            this.EndTime = endTime;
            this.Title = title;
            this.IsDone = isDone;
        }
    }
}
