//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainCenter.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Visiting
    {
        public int id { get; set; }
        public Nullable<int> AbonementId { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string Commentary { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }

        public virtual Abonement Abonement { get; set; }

        public Visiting()
        {

        }
        public Visiting(int abonementId, string commentary, TimeSpan startTime, TimeSpan endTime)
        {
            this.AbonementId = abonementId;
            this.VisitDate = DateTime.Now;
            this.Commentary = commentary;
            this.StartTime = startTime;
            this.EndTime = endTime;
        }
    }
}
